FROM ghcr.io/cdot65/ansible-ee-paloaltonetworks:dev

# ---------------------------------------------------------------------------
# Metadata
# ---------------------------------------------------------------------------
LABEL name="ghcr.io/cdot65/pan-os-docker"
LABEL maintainer="cremsburg.dev@gmail.com"
LABEL description="Ansible container for Palo Alto Networks products."
LABEL license="Apache 2.0"
LABEL url="https://github.com/cdot65/pan-os-docker"
LABEL build-date="20221126"

# ---------------------------------------------------------------------------
# Setup environment
# ---------------------------------------------------------------------------
WORKDIR /home/ansible
